---
name: OCaml Build

on:
  push:
    paths:
      - 'src/**/*.ml'
      - 'src/**/*.mli'
      - 'test/**/*.ml'
      - '**/dune'
      - 'duneproject'
      - '.github/workflows/ocaml.yml'
      - '*.opam'
  pull_request:
    paths:
      - 'src/**/*.ml'
      - 'src/**/*.mli'
      - 'test/**/*.ml'
      - '**/dune'
      - 'dune-project'
      - '.github/workflows/ocaml.yml'
      - '*.opam'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup OCaml
      uses: avsm/setup-ocaml@v2
      with:
        ocaml-compiler: '5.1'

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y opam
        opam init -y
        opam install -y dune ocamlformat

    - name: Lint with OCamlformat
      run: |
        eval $(opam env)
        ocamlformat --check src/*.ml src/*.mli test/*.ml

    - name: Build
      run: |
        eval $(opam env)
        dune build @all

    - name: Run Tests
      run: |
        eval $(opam env)
        dune runtest

